[package]
name = "ironrift"
version = "0.1.0"
edition = "2018"

[dependencies]
bevy = "0.5"
bevy_rapier3d = { version = "*", features = [ "simd-nightly" ] }
nalgebra = { version = "*", features = [ "convert-glam", "convert-glam-unchecked" ] }
